Update woocommerce to getService v16 and make paymentOption logos local.
paynl/woocommerce-plugin pull request #14
Opened 2020-07-15 12:14 UTC by kevinverschoor

2020-07-20 09:45 UTC, woutse requested changes
![afbeelding](https://user-images.githubusercontent.com/6763638/87923921-783a5400-ca7e-11ea-82af-e87fc90852d5.png)


Daarnaast zie ik dat je de vendor files hebt aangepast. 
Dit terugdraaien en gebruik maken van de de nieuwste SDK waar je dit al in hebt gemaakt.

2020-07-30 14:56 UTC, annevelden approved these changes

2020-08-02 21:21 UTC, woutse requested changes
See private messages

2020-08-06 12:52 UTC, annevelden approved these changes

2020-08-09 18:12 UTC, woutse commented on includes/classes/Pay/Gateway/Abstract.php
> +          return PAYNL_PLUGIN_URL . '/assets/logos/' . $this->get_option('brand_id') . '.png';
De eerste slash voor assets kan er af. 
De code is nu ook wat vreemd, want wat doet size nu nog?
Kunnen de images in de checkout wat groter? Ik vind het prima als we $size hiervoor gebruiken.

2020-08-09 18:24 UTC, woutse requested changes
see comments

2020-08-11 14:46 UTC, bryantvandenberg approved these changes

2020-08-11 14:56 UTC, annevelden approved these changes

2020-08-12 08:56 UTC, woutse approved these changes

2020-08-12 08:56 UTC, merged