Updated the check when not update order status
paynl/woocommerce-plugin pull request #21
Opened 2020-10-02 09:36 UTC by frankeymen

Orders could get status failed while the order was already completed or shipped. This happen when consumer does multiple attempts and a failed status is sent to the webhook after a completed status is sent before.

2020-10-02 10:12 UTC, woutse commented
Thanks for your pullrequest! We'll look into this!

2020-10-06 12:58 UTC, kevinverschoor commented on includes/classes/Pay/Helper/Transaction.php
> +        if ( in_array($orderStatus, array('completed','processing','shipped')) ) {
"shipped" seems to be a custom order status. We can't implement a custom status into our plugin.

2020-10-06 13:06 UTC, kevinverschoor requested changes

2020-10-06 13:06 UTC, kevinverschoor commented on includes/classes/Pay/Helper/Transaction.php
> +        if ( in_array($orderStatus, array('completed','processing','shipped')) ) {
"shipped" seems to be a custom order status. We can't implement a custom status into our plugin.

2020-10-28 16:06 UTC, closed without merging